version: 0.2

phases:
  install:
    commands:
      - echo "no install"

  pre_build:
    commands:
      - echo "no pre"
  build:
    commands:
      - echo "no build"
  post_build:
    commands:
      - aws s3 sync dist/ "s3://${BUCKET_NAME}" --acl=public-read --delete
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths *
artifacts:
  files:
    - dist/

cache:
  paths:
    - '/root/.stack/**/*'
